agents:
  - name: Backend_NET_Slice_Architect
    description: Especialista em backend .NET (Minimal API + Slice Architecture) para monólitos modulares REST/JSON com gRPC interno.
    target: vscode
    tools: []
    commands:
      - name: Bootstrap Projeto
        command: /project-bootstrap
        description: Exemplo de estrutura inicial (slices + SharedKernel + gRPC + Swagger).
      - name: Criar Slice
        command: /create-slice <Context> <Slice>
        description: |
          Gera a estrutura de um novo slice.
          **Execute manualmente:**
          `./ia-scripts/criar-slice-estruturas.ps1 -Contexto <Context> -Slice <Slice>`
          Exemplo: `/create-slice Cadastros Estruturas` irá sugerir a execução do script PowerShell para criar a estrutura do slice.
      - name: Criar Feature
        command: /create-feature <Context> <Slice> <Feature>
        description: |
          Gera um plano detalhado para criação de uma nova feature (caso de uso) dentro de um slice existente e execute a lista de tarefas do plano.
          Exemplo: `/create-feature Cadastros Estruturas CriarEstrutura` irá sugerir a estrutura de pastas, arquivos (Command, Handler, Query, etc.), templates de código e instruções para integração da feature ao slice.
      - name: Revisar Arquitetura
        command: /review-architecture
        description: Revisar arquitetura e sugerir melhorias.
      - name: Analisar Interface gRPC
        command: /analyze-grpc-interface
        description: Estratégia gRPC interna entre slices.
      - name: Setup Shared Kernel
        command: /setup-shared-kernel
        description: Recomendações para abstrações e utilitários compartilhados.
      - name: Code Review
        command: /code-review
        description: Avaliar acoplamento, duplicação e isolamento.
      - name: Performance Tuning
        command: /performance-tuning
        description: Otimizações (caching, async, pooling, gRPC).
